apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: core-user-password
spec:
  config:
    ignition:
      version: 3.4.0
    passwd:
      users:
      - name: core 
        passwordHash: $6$9Xxnopc2lh.7C5T5$mLcqVtmUyas.3C0E3oQNupGRbxtVhncxIm.WtGHdwN.Z7gHROdDXQzuD0XS95NDD912WmnB.QnLx5wX2FN4Tl/
