---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: openshift-gitops-operator
    namespace: openshift-operators
spec:
    installPlanApproval: Automatic
    name: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace