---
apiVersion: v1
kind: Secret
metadata:
  name: worker1-nmstate-secret
  namespace: openshift-machine-api
type: Opaque
stringData:
  nmstate: |
    interfaces: 
    - name: eth0 
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.58.40
          prefix-length: 25
        enabled: true
      ipv6:
        enabled: false
    dns-resolver:
      config:
        server:
        - 192.168.58.15
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.58.1
        next-hop-interface: eth0