cluster:
  domain: outbound.vz.bos2.lab
  name: compact
  apiVIPs:
    - 192.168.58.90
    #- 2600:52:7:58::90
  ingressVIPs:
    - 192.168.58.91
    #- 2600:52:7:58::91

hosts:
  common:
    ipv4:
      enabled: true
      dhcp: false
      machine_network_cidr: 192.168.58.0/25
      machine_network_prefix: 25
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 192.168.58.15
      gateway: 192.168.58.1
    ipv6:
      enabled: false
      dhcp: false
      machine_network_cidr: 2600:52:7:58::/64
      machine_network_prefix: 64
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 2600:52:7:58::15
      gateway: 2600:52:7:58::1
    bond:
      mode: 802.3ad
      miimon: 100
    vlan:
      enabled: false
      name: ens1f0.58
      id: 58
    disk: /dev/vda
    bmc:
      bypass_proxy: true

  masters:
    - hostname: master0.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: bond0
      bond:
        members:
          - interface: ens1f0
            mac: de:ad:be:ff:10:30
          - interface: ens1f
            mac: de:ad:be:ff:10:31
      mac: de:ad:be:ff:10:30
      ipv4:
        ip: 192.168.58.30
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000000
    - hostname: master1.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: ens1f0
      mac: de:ad:be:ff:10:31
      ipv4:
        ip: 192.168.58.31
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000001
    - hostname: master2.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: ens1f0
      mac: de:ad:be:ff:10:32
      ipv4:
        ip: 192.168.58.32
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000002
  workers:
    - hostname: worker0.compact.outbound.vz.bos2.lab
      roles:
        - worker-hp
        - others
      labels:
        - e810-nic-present
      interface: ens1f0
      mac: de:ad:be:ff:10:40
      ipv4:
        ip: 192.168.58.40
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0010-000000000040
    - hostname: worker0.compact.outbound.vz.bos2.lab
      roles:
        - worker-hp
        - others
      labels:
        - e700-nic-present
      interface: ens1f0
      mac: de:ad:be:ff:10:41
      ipv4:
        ip: 192.168.58.41
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0010-000000000041

proxy:
  enabled: false
  http:
  https:
  noproxy:

day1:
  crun: false
  operators:
    ptp:
      enabled: false
      source: redhat-operators
    sriov:
      enabled: true
      source: redhat-operators
    local-storage:
      enabled: true
      source: redhat-operators
    lvm:
      enabled: false
      source: redhat-operators
    odf:
      enabled: true
      source: redhat-operators
    rhacm:
      enabled: false
      source: redhat-operators
    mce:
      enabled: false
      source: redhat-operators
    gitops:
      enabled: false
      source: redhat-operators
    talm:
      enabled: false
      source: redhat-operators
    nmstate:
      enabled: true
      source: redhat-operators
    metallb:
      enabled: true
      source: redhat-operators
day2:
  node_labels_enabled: true
  disable_operator_auto_upgrade: true
  mcp:
    - name: "worker-hp"
      role: "worker-hp"
      performance_profile:
        enabled: true
        name: performance-profile-worker-hp
        #manifest can be yaml or j2 template file, find from extra-manifests/day2/performance-profiles/ if a relative path provided
        manifest: performance-profile-worker-hp.yaml.j2
        #following are free format, used to build the performance-profile based on the j2 template
        cpu:
          isolated: "2-13,16-27,30-41,44-55"
          reserved: "0,28,1,29,14,42,15,43"
        hugepages:
          default: 2M
          pages:
            - size: 2M
              count: 32768
              #node: 1
        numa:
          policy: "single-numa-node"
  # will find from extra-manifests/performance-profiles/ by default, support yaml files only?
  performance_profiles:
    - profile-worker.yaml
    - profile-others.yaml
  tuned_profiles:
    - tuned-worker.yaml
    - tuned-others.yaml
  operators:
    nmstate:
      ## will find yaml or j2 files from extra-manifests/day2/nmstate/* by default if not present
      #crs: extra-manifests/day2/nmstate/
      # will find sh files from extra-manifests/day2/nmstate/* by default if not present
      #scripts: extra-manifests/day2/nmstate/
    metallb:
      ## will find yaml or j2 files from extra-manifests/day2/nmstate/* by default if not present
      #crs: extra-manifests/day2/metallb/
      # will find sh files from extra-manifests/day2/metallb/* by default if not present
      #scripts: extra-manifests/day2/metallb/
    local-storage:
      ## will find yaml or j2 files from extra-manifests/day2/local-storage/* by default if not present
      #crs: extra-manifests/day2/local-storage/
      # will find sh files from extra-manifests/day2/local-storage/* by default if not present
      #scripts: extra-manifests/day2/local-storage/
    whatever:
      ## will find yaml or j2 files from extra-manifests/day2/whatever/* by default if not present
      #crs: extra-manifests/day2/whatever/
      # will find sh files from extra-manifests/day2/whatever/* by default if not present
      #scripts: extra-manifests/day2/whatever/

additional_trust_bundle: /root/registry/ca-bundle.crt
pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

iso:
  address: http://192.168.58.15/iso/compact.iso