cluster:
  domain: outbound.vz.bos2.lab
  name: cluster6
  apiVIPs:
    - 192.168.58.60
    #- 2600:52:7:58::60
  ingressVIPs:
    - 192.168.58.67
    #- 2600:52:7:58::67
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org

hosts:
  common:
    ipv4:
      enabled: true
      dhcp: false
      machine_network_cidr: 192.168.58.0/25
      machine_network_prefix: 25
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 192.168.58.15
      gateway: 192.168.58.1
    ipv6:
      enabled: false
      dhcp: false
      machine_network_cidr: 2600:52:7:58::/64
      machine_network_prefix: 64
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 2600:52:7:58::15
      gateway: 2600:52:7:58::1
    bond:
      mode: 802.3ad
      miimon: 100
    vlan:
      enabled: false
      name: ens1f0.58
      id: 58
    disk: /dev/vda
    bmc:
      bypass_proxy: true

  masters:
    - hostname: master1.cluster6.outbound.vz.bos2.lab
      interface: ens1f0
      mac: de:ad:be:ff:10:61
      ipv4:
        ip: 192.168.58.61
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000061
    - hostname: master2.cluster6.outbound.vz.bos2.lab
      interface: ens1f0
      mac: de:ad:be:ff:10:62
      ipv4:
        ip: 192.168.58.62
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000062
    - hostname: master3.cluster6.outbound.vz.bos2.lab
      interface: ens1f0
      mac: de:ad:be:ff:10:63
      ipv4:
        ip: 192.168.58.63
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000063
  workers:
    - hostname: worker1.cluster6.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        # marked for providing disk for ODF deployment
        - cluster.ocs.openshift.io/openshift-storage=
      interface: ens1f0
      mac: de:ad:be:ff:10:64
      ipv4:
        ip: 192.168.58.64
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000064
    - hostname: worker2.cluster6.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        # marked for providing disk for ODF deployment
        - cluster.ocs.openshift.io/openshift-storage=
      interface: ens1f0
      mac: de:ad:be:ff:10:65
      ipv4:
        ip: 192.168.58.65
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000065
    - hostname: worker3.cluster6.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        # marked for providing disk for ODF deployment
        - cluster.ocs.openshift.io/openshift-storage=
      interface: ens1f0
      mac: de:ad:be:ff:10:66
      ipv4:
        ip: 192.168.58.66
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-111100000066

proxy:
  enabled: false
  http:
  https:
  noproxy:

day1:
  crun: false
  operators:
    ptp:
      enabled: false
      source: redhat-operators
    sriov:
      enabled: true
      source: redhat-operators
    local-storage:
      enabled: true
      source: redhat-operators
    lvm:
      enabled: false
      source: redhat-operators
    odf:
      enabled: true
      source: redhat-operators
    rhacm:
      enabled: false
      source: redhat-operators
    mce:
      enabled: false
      source: redhat-operators
    gitops:
      enabled: false
      source: redhat-operators
    talm:
      enabled: false
      source: redhat-operators
    nmstate:
      enabled: true
      source: redhat-operators
    metallb:
      enabled: true
      source: redhat-operators
    cluster-logging:
      enabled: false
      source: redhat-operators

day2:
  node_labels_enabled: true
  disable_operator_auto_upgrade: true
  mcp:
    - name: "worker-hp"
      role: "worker-hp"
      performance_profile:
        enabled: true
        name: performance-profile-worker-hp
        #manifest can be yaml or j2 template file, find from extra-manifests/day2/performance-profiles/ if a relative path provided
        manifest: performance-profile-worker-hp.yaml.j2
        #following are free format, used to build the performance-profile based on the j2 template
        cpu:
          isolated: "2-13,16-27,30-41,44-55"
          reserved: "0,28,1,29,14,42,15,43"
        hugepages:
          default: 2M
          pages:
            - size: 2M
              count: 32768
              #node: 1
        numa:
          policy: "single-numa-node"
  # will find from extra-manifests/performance-profiles/ by default, support yaml files only?
  #performance_profiles:
    #- profile-worker.yaml
    #- profile-others.yaml
  #tuned_profiles:
    #- tuned-worker.yaml
    #- tuned-others.yaml
  operators:
    #op:
      #Supported 'op' can be found from operators/operators.yaml. For example: local-storage or nmstate
      #Put additional crs desired to be applied towards the operator in folder extra-manifests/day2/$op/, can support yaml or j2 file;
      #The yaml files together with the rendered files based on j2 templates will be executed with a respected order by file name.
      #Put bash scripts desired to be executed in folder extra-manifests/day2/$op/, can support *.sh
      #Other free-format data to define variables, used to build the extra-manifests based on the template provided in extra-manifests/day2/$op/
    #following is an example for metallb operator, #to add more examples.
    metallb:
      selector:
        role: "worker"

#set it in a disconnected env
additional_trust_bundle: /root/registry/ca-bundle.crt
#set it in a disconnected env, mirror/mirror-operators.sh can be used to generate the file
mirror_source: /root/registry/local-mirror.yaml

pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

iso:
  address: http://192.168.58.15/iso/compact.iso