cluster:
  domain: outbound.vz.bos2.lab
  name: compact
  apiVIPs:
    - 192.168.58.90
    #- 2600:52:7:58::90
  ingressVIPs:
    - 192.168.58.91
    #- 2600:52:7:58::91

hosts:
  common:
    ipv4:
      enabled: true
      dhcp: false
      machine_network_cidr: 192.168.58.0/25
      machine_network_prefix: 25
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 192.168.58.15
      gateway: 192.168.58.1
    ipv6:
      enabled: false
      dhcp: false
      machine_network_cidr: 2600:52:7:58::/64
      machine_network_prefix: 64
      #cluster_network_cidr:
      #cluster_network_host_prefix:
      #service_network:
      dns: 2600:52:7:58::15
      gateway: 2600:52:7:58::1
    bond:
      mode: 802.3ad
      miimon: 100
    vlan:
      enabled: false
      name: ens1f0.58
      id: 58
    disk: /dev/vda
    bmc:
      bypass_proxy: true

  masters:
    - hostname: master0.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: bond0
      bond:
        members:
          - interface: ens1f0
            mac: de:ad:be:ff:10:30
          - interface: ens1f
            mac: de:ad:be:ff:10:31
      mac: de:ad:be:ff:10:30
      ipv4:
        ip: 192.168.58.30
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000000
    - hostname: master1.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: ens1f0
      mac: de:ad:be:ff:10:31
      ipv4:
        ip: 192.168.58.31
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000001
    - hostname: master2.compact.outbound.vz.bos2.lab
      roles:
        - infra
      labels:
        - cluster.ocs.openshift.io/openshift-storage=""
      interface: ens1f0
      mac: de:ad:be:ff:10:32
      ipv4:
        ip: 192.168.58.32
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0000-000000000002
  workers:
    - hostname: worker0.compact.outbound.vz.bos2.lab
      roles:
        - worker-hp
        - others
      labels:
        - e810-nic-present
      interface: ens1f0
      mac: de:ad:be:ff:10:40
      ipv4:
        ip: 192.168.58.40
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0010-000000000040
    - hostname: worker0.compact.outbound.vz.bos2.lab
      roles:
        - worker-hp
        - others
      labels:
        - e700-nic-present
      interface: ens1f0
      mac: de:ad:be:ff:10:41
      ipv4:
        ip: 192.168.58.41
      bmc:
        address: 192.168.58.15:8080
        password: Administrator:dummy
        node_uuid: 22222222-1111-1111-0010-000000000041

proxy:
  enabled: false
  http:
  https:
  noproxy:

day1:
  crun: false
  operators:
    ptp: false
    sriov: true
    local_storage: true
    lvm: false
    odf: true
    rhacm: false
    mce: false
    gitops: false
    talm: false
    nmstate: true
    metallb: true

day2:
  node_labels:
    enabled: true

pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub

iso:
  address: http://192.168.58.15/iso/compact.iso