apiVersion: v1
metadata:
  name: compact
baseDomain: outbound.vz.bos2.lab
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.58.0/25
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVips:
    - 192.168.58.90
    hosts:    
    - bootMACAddress: de:ad:be:ff:10:30
      name: master1.compact.outbound.vz.bos2.lab
      role: master
    
    - bootMACAddress: de:ad:be:ff:10:31
      name: master2.compact.outbound.vz.bos2.lab
      role: master
    
    - bootMACAddress: de:ad:be:ff:10:32
      name: master3.compact.outbound.vz.bos2.lab
      role: master
    
    - bootMACAddress: de:ad:be:ff:10:33
      name: worker1.compact.outbound.vz.bos2.lab
      role: worker
    
    - bootMACAddress: de:ad:be:ff:10:34
      name: worker2.compact.outbound.vz.bos2.lab
      role: worker
    
    ingressVips:
    - 192.168.58.91
pullSecret: 'None'
sshKey: 'None'