apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  sources:
  - disabled: true
    name: redhat-marketplace
  - disabled: true
    name: community-operators
  - disabled: true
    name: redhat-operators
  - disabled: true
    name: certified-operators
